source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord', '~> 4.1'
gem 'thin'
gem 'execjs'
gem 'coffee-script'
gem 'activesupport', '~> 4.1'
gem 'sinatra-activerecord'
gem 'json'
gem 'sqlite3'
gem 'rerun'
gem 'multi_json'
